### ISSUE TITLE
ISO 8601 Datum bei Schulferien

### ISSUE THREAD

**Issue by metaodi** [opendatazurich/opendatazurich.github.io#40]
Mit `strftime` kann ein gültiges ISO 8601 Datum exportiert werden bei den Schulferien:

https://github.com/opendatazurich/opendatazurich.github.io/blob/dc60ae20f83c56a69e343eb50480260cdf21511e/automation/schulferien/run_scraper.sh#L29

```
select strftime('%Y-%m-%dT%H:%M:%S', start_date) as start_date, ....
```

**Comment by DonGoginho** [comment]
done with the update ;)
